theme: jekyll-theme-midnight
title: Vishnu Ravi Varma's Showcase of Collective Madness
description: Designed to immemorialise my subjectively great code and possibly get incentivised as a result of it.
