theme: jekyll-theme-midnight
title: Vishnu Ravi Varma's Showcase of Collective Madness
description: Designed to immemeorialise my subjectively **great** code and possibly get incentivised(_Fingers Crossed_) as a result of it.
